# Generated by Django 5.2.7 on 2025-10-26 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "admission_code",
                    models.CharField(
                        blank=True,
                        help_text="Tùy chọn: mã tham chiếu tới Điểm chuẩn",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("subject_combinations", models.CharField(blank=True, max_length=255)),
                ("tuition", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("HN", "Hà Nội"),
                            ("HCM", "TP HCM"),
                            ("DN", "Đà Nẵng"),
                            ("OTHER", "Khác"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Admission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=50, null=True)),
                ("score", models.FloatField(blank=True, null=True)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admissions",
                        to="base.program",
                    ),
                ),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
        migrations.AddField(
            model_name="program",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="base.school",
            ),
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_score",
                    models.FloatField(blank=True, help_text="Điểm mục tiêu", null=True),
                ),
                ("ielts_score", models.FloatField(blank=True, null=True)),
                ("hsa_score", models.FloatField(blank=True, null=True)),
                ("tsa_score", models.FloatField(blank=True, null=True)),
                (
                    "transcript",
                    models.FileField(blank=True, null=True, upload_to="transcripts/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="base.program",
                    ),
                ),
                (
                    "target_school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="base.school",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HsaExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(help_text="Đợt thi HSA thứ mấy"),
                ),
                ("subject1_name", models.CharField(blank=True, max_length=100)),
                ("subject1_score", models.FloatField(blank=True, null=True)),
                ("subject2_name", models.CharField(blank=True, max_length=100)),
                ("subject2_score", models.FloatField(blank=True, null=True)),
                ("subject3_name", models.CharField(blank=True, max_length=100)),
                ("subject3_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hsa_exams",
                        to="base.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrialExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(help_text="Đợt thi thử thứ mấy"),
                ),
                ("subject1_name", models.CharField(blank=True, max_length=100)),
                ("subject1_score", models.FloatField(blank=True, null=True)),
                ("subject2_name", models.CharField(blank=True, max_length=100)),
                ("subject2_score", models.FloatField(blank=True, null=True)),
                ("subject3_name", models.CharField(blank=True, max_length=100)),
                ("subject3_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trial_exams",
                        to="base.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TsaExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(help_text="Đợt thi TSA thứ mấy"),
                ),
                ("subject1_name", models.CharField(blank=True, max_length=100)),
                ("subject1_score", models.FloatField(blank=True, null=True)),
                ("subject2_name", models.CharField(blank=True, max_length=100)),
                ("subject2_score", models.FloatField(blank=True, null=True)),
                ("subject3_name", models.CharField(blank=True, max_length=100)),
                ("subject3_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tsa_exams",
                        to="base.studentprofile",
                    ),
                ),
            ],
        ),
    ]
