# Generated by Django 5.2.7 on 2025-10-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="region",
            field=models.CharField(
                choices=[
                    ("HN", "Hà Nội"),
                    ("HCM", "TP HCM"),
                    ("DN", "Đà Nẵng"),
                    ("CT", "Cần Thơ"),
                    ("OTHER", "Khác"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
