# Generated by Django 5.2.7 on 2025-10-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_studentprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="address",
            field=models.TextField(blank=True, default="", verbose_name="Địa chỉ"),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="age",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Tuổi"
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="full_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Họ và tên"
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Số điện thoại"
            ),
        ),
    ]
