# Generated by Django 5.2.7 on 2025-10-30 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_studentprofile_address_studentprofile_age_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hsaexam",
            name="attempt_number",
        ),
        migrations.RemoveField(
            model_name="trialexam",
            name="attempt_number",
        ),
        migrations.RemoveField(
            model_name="tsaexam",
            name="attempt_number",
        ),
    ]
