# Generated by Django 5.2.7 on 2025-10-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_remove_hsaexam_attempt_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hsaexam",
            name="subject1_name",
        ),
        migrations.RemoveField(
            model_name="hsaexam",
            name="subject2_name",
        ),
        migrations.RemoveField(
            model_name="hsaexam",
            name="subject3_name",
        ),
        migrations.RemoveField(
            model_name="tsaexam",
            name="subject1_name",
        ),
        migrations.RemoveField(
            model_name="tsaexam",
            name="subject2_name",
        ),
        migrations.RemoveField(
            model_name="tsaexam",
            name="subject3_name",
        ),
        migrations.AlterField(
            model_name="hsaexam",
            name="subject1_score",
            field=models.FloatField(blank=True, null=True, verbose_name="Điểm môn 1"),
        ),
        migrations.AlterField(
            model_name="hsaexam",
            name="subject2_score",
            field=models.FloatField(blank=True, null=True, verbose_name="Điểm môn 2"),
        ),
        migrations.AlterField(
            model_name="hsaexam",
            name="subject3_score",
            field=models.FloatField(blank=True, null=True, verbose_name="Điểm môn 3"),
        ),
        migrations.AlterField(
            model_name="tsaexam",
            name="subject1_score",
            field=models.FloatField(blank=True, null=True, verbose_name="Điểm môn 1"),
        ),
        migrations.AlterField(
            model_name="tsaexam",
            name="subject2_score",
            field=models.FloatField(blank=True, null=True, verbose_name="Điểm môn 2"),
        ),
        migrations.AlterField(
            model_name="tsaexam",
            name="subject3_score",
            field=models.FloatField(blank=True, null=True, verbose_name="Điểm môn 3"),
        ),
    ]
