# Generated by Django 5.2.7 on 2025-10-30 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_remove_hsaexam_subject1_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hsaexam",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="trialexam",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tsaexam",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="hsaexam",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hsa_exams",
                to="base.studentprofile",
            ),
        ),
        migrations.AlterField(
            model_name="trialexam",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trial_exams",
                to="base.studentprofile",
            ),
        ),
        migrations.AlterField(
            model_name="tsaexam",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tsa_exams",
                to="base.studentprofile",
            ),
        ),
    ]
