# Generated by Django 5.2.7 on 2025-10-30 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_hsaexam_updated_at_trialexam_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hsaexam",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="trialexam",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="tsaexam",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="hsaexam",
            name="attempt_number",
            field=models.PositiveIntegerField(default=1, verbose_name="Lần thi thứ"),
        ),
        migrations.AddField(
            model_name="trialexam",
            name="attempt_number",
            field=models.PositiveIntegerField(default=1, verbose_name="Lần thi thứ"),
        ),
        migrations.AddField(
            model_name="tsaexam",
            name="attempt_number",
            field=models.PositiveIntegerField(default=1, verbose_name="Lần thi thứ"),
        ),
        migrations.AlterField(
            model_name="hsaexam",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hsa_exams",
                to="base.studentprofile",
            ),
        ),
        migrations.AlterField(
            model_name="trialexam",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trial_exams",
                to="base.studentprofile",
            ),
        ),
        migrations.AlterField(
            model_name="tsaexam",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tsa_exams",
                to="base.studentprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hsaexam",
            unique_together={("student", "attempt_number")},
        ),
        migrations.AlterUniqueTogether(
            name="trialexam",
            unique_together={("student", "attempt_number")},
        ),
        migrations.AlterUniqueTogether(
            name="tsaexam",
            unique_together={("student", "attempt_number")},
        ),
    ]
