# Generated by Django 5.2.7 on 2025-10-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_hsaexam_options_alter_trialexam_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="type",
            field=models.CharField(
                choices=[
                    ("khoa_hoc_cong_nghe", "Khoa học – Công nghệ – Kỹ thuật"),
                    ("giao_duc_du_lich", "Giáo dục – Du lịch – Dịch vụ"),
                    ("toan_thong_ke", "Toán – Thống kê – Khoa học dữ liệu"),
                    ("nong_lam_ngu", "Nông – Lâm – Ngư nghiệp – Môi trường"),
                    ("nghe_thuat_thiet_ke", "Nghệ thuật – Thiết kế – Truyền thông"),
                    ("luat_hanh_chinh", "Luật – Hành chính – Chính trị – Xã hội"),
                    ("kinh_te_quan_tri", "Kinh tế – Quản trị – Tài chính"),
                ],
                default="khoa_hoc_cong_nghe",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
