# Generated by Django 5.2.7 on 2025-10-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_program_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="decription",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="program",
            name="tuition",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
