# Generated by Django 5.2.7 on 2025-10-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_school_decription_alter_program_tuition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="transcript",
        ),
        migrations.AddField(
            model_name="school",
            name="transcript",
            field=models.FileField(blank=True, null=True, upload_to="transcripts/"),
        ),
        migrations.AddField(
            model_name="school",
            name="type_school",
            field=models.CharField(
                choices=[("DH", "Đại học"), ("CĐ", "Cao đẳng"), ("TC", "Trung cấp")],
                default="DH",
                max_length=2,
            ),
        ),
    ]
