# Generated by Django 5.2.7 on 2025-11-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_remove_studentprofile_transcript_school_transcript_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hsaexam",
            name="date_exam",
            field=models.DateField(blank=True, null=True, verbose_name="Ngày thi"),
        ),
        migrations.AddField(
            model_name="trialexam",
            name="date_exam",
            field=models.DateField(blank=True, null=True, verbose_name="Ngày thi"),
        ),
        migrations.AddField(
            model_name="tsaexam",
            name="date_exam",
            field=models.DateField(blank=True, null=True, verbose_name="Ngày thi"),
        ),
    ]
