# Generated by Django 5.2.7 on 2025-11-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_chatconversation_chatmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="hsa_score",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="tsa_score",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="target_program_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("khoa_hoc_cong_nghe", "Khoa học – Công nghệ – Kỹ thuật"),
                    ("giao_duc_du_lich", "Giáo dục – Du lịch – Dịch vụ"),
                    ("toan_thong_ke", "Toán – Thống kê – Khoa học dữ liệu"),
                    ("nong_lam_ngu", "Nông – Lâm – Ngư nghiệp – Môi trường"),
                    ("nghe_thuat_thiet_ke", "Nghệ thuật – Thiết kế – Truyền thông"),
                    ("luat_hanh_chinh", "Luật – Hành chính – Chính trị – Xã hội"),
                    ("kinh_te_quan_tri", "Kinh tế – Quản trị – Tài chính"),
                ],
                max_length=255,
                null=True,
                verbose_name="Nhóm ngành mục tiêu",
            ),
        ),
    ]
